Eraware_Dnn_Spa_Ef_Di_Stencil/build/docs/articles/intro.html
Correct small typo in getting started
=> Correct small typo in getting started

Eraware_Dnn_Spa_Ef_Di_Stencil/IntegrationTests/ProjectTemplate.csproj, Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/ProjectTemplate.csproj, Eraware_Dnn_Spa_Ef_Di_Stencil/module/ProjectTemplate.csproj, Eraware_Dnn_Spa_Ef_Di_Stencil/module/manifest.dnn
Bumped DNN dependency to v9.10.1
=> Bumped DNN dependency to v9.10.1

README.md
=> Adds some readme documentation

Eraware_Dnn_Spa_Ef_Di_Stencil/module.web/package.json
Bump @typescript-eslint/parser from 4.31.0 to 4.31.1 in /module.web
=> Bump @typescript-eslint/parser from 4.31.0 to 4.31.1 in /module.web

Eraware_Dnn_Spa_Ef_Di_Stencil/module.web/package.json
Bump typescript from 4.4.2 to 4.4.3 in /module.web
=> Bump typescript from 4.4.2 to 4.4.3 in /module.web

Eraware_Dnn_Spa_Ef_Di_Stencil/module.web/package.json
Bump @microsoft/api-extractor from 7.18.7 to 7.18.9 in /module.web
=> Bump @microsoft/api-extractor from 7.18.7 to 7.18.9 in /module.web

Eraware_Dnn_Spa_Ef_Di_Stencil/module.web/package.json
Bump @microsoft/api-documenter from 7.13.44 to 7.13.49 in /module.web
=> Bump @microsoft/api-documenter from 7.13.44 to 7.13.49 in /module.web

Eraware_Dnn_Spa_Ef_Di_Stencil/build/Build.cs, Eraware_Dnn_Spa_Ef_Di_Stencil/module/docfx_project/articles/git.md
Adds support for both `main` or `master` branch as the main branch
=> Added support for both `main` or `master` branch as the main branch

Eraware_Dnn_Spa_Ef_Di_Stencil/build/Build.cs, Eraware_Dnn_Spa_Ef_Di_Stencil/build/ProjectTemplate.csproj
=> Bump ReportGenerator from 4.8.13 to 5.0.0

Eraware_Dnn_Spa_Ef_Di_Stencil/build/ProjectTemplate.csproj, Eraware_Dnn_Spa_Ef_Di_Stencil/module/ProjectTemplate.csproj, Eraware_Dnn_Spa_Ef_Di_Stencil/module/manifest.dnn
Bump NSwag from 13.13.2 to 13.14.8
=> Bump NSwag from 13.13.2 to 13.14.8

Eraware_Dnn_Spa_Ef_Di_Stencil/build/Build.cs, Eraware_Dnn_Spa_Ef_Di_Stencil/module.web/package.json
Fixed an issue that prevented running Package without git repository
=> Fixed an issue that prevented running Package without git repository

Eraware_Dnn_Templates/Properties/AssemblyInfo.cs
=> Bumped version to v1.0.1

Eraware_Dnn_Templates/source.extension.vsixmanifest
Properly set version to v1.0.1
=> Properly set version to v1.0.1

Eraware_Dnn_Templates/Properties/AssemblyInfo.cs, Eraware_Dnn_Templates/source.extension.vsixmanifest
=> Released v1.0.1

Eraware_Dnn_Templates.sln, Eraware_Dnn_Templates/Eraware_Dnn_Templates.csproj, Eraware_Dnn_Templates/LICENSE, Eraware_Dnn_Templates/source.extension.vsixmanifest, LICENSE
Added support for Visual Studio 2022
=> Added support for Visual Studio 2022

Eraware_Dnn_Templates/source.extension.vsixmanifest
Bumps version to v1.1.0 for next release
=> Bumps version to v1.1.0 for next release

Eraware_Dnn_Spa_Ef_Di_Stencil/build/Build.cs, Eraware_Dnn_Spa_Ef_Di_Stencil/build/Helpers.cs, Eraware_Dnn_Spa_Ef_Di_Stencil/build/ProjectTemplate.csproj, Eraware_Dnn_Spa_Ef_Di_Stencil/module/global.json, Eraware_Dnn_Templates/WizardImplementation.cs
Updated nuke to v6.0.1 and made related adjustments.
Supercedes #432
=> Updated nuke to v6.0.1

Eraware_Dnn_Templates/source.extension.vsixmanifest
Fixed a wrong vsix manifest declaration
Closes #434
=> Fixed a wrong vsix manifest declaration

Eraware_Dnn_Templates/source.extension.vsixmanifest
More vsix adjustments to support 2019 and 2022 in same extensions
=> More vsix adjustments to support 2019 and 2022 in same extensions

Eraware_Dnn_Spa_Ef_Di_Stencil/module/docfx_project/articles/intro.md
=> Added a note about the build project not being the startup project

Eraware_Dnn_Spa_Ef_Di_Stencil/module/docfx_project/articles/intro.md
Improved UX for next step after initial setup
=> Improved UX for next step after initial setup

Eraware_Dnn_Spa_Ef_Di_Stencil/build/Helpers.cs
Fixed a missed deprecated usage of the Logger class
=> Fixed a missed deprecated usage of the Logger class

Eraware_Dnn_Spa_Ef_Di_Stencil/build/Helpers.cs
Added support for root folder containing a dot
=> Added support for root folder containing a dot

Eraware_Dnn_Spa_Ef_Di_Stencil/build/Build.cs, Eraware_Dnn_Spa_Ef_Di_Stencil/module/Controllers/ValidateModelAttribute.cs, Eraware_Dnn_Templates/WizardImplementation.cs, Eraware_Dnn_Templates/source.extension.vsixmanifest
This caused the watch task to have wrong paths, closes #448
=> Fixed an issue when the folder name was not the project name

.github/mergeable.yml
Getting some odd invalid messages at times and I have a theory that maybe some whitespace or line ending is wrong, trying to resave it to see.
=> Resaved mergeable config file

Eraware_Dnn_Spa_Ef_Di_Stencil/build/Build.cs
Fixed 3 missing comas in the build.cs file
=> Fixed 3 missing comas in the build.cs file

Eraware_Dnn_Spa_Ef_Di_Stencil/module/.github/workflows/Build.yml
Includes missing `main` branch in workflows
=> Includes missing `main` branch in workflows

Eraware_Dnn_Templates/source.extension.vsixmanifest
Bumped version to 1.3.1 for next release
=> Bumped version to 1.3.1 for next release

Eraware_Dnn_Spa_Ef_Di_Stencil/build/ProjectTemplate.csproj
Bumped report generator to v5.1.0
=> Bumped report generator to v5.1.0

Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/Data/Repositories/GenericRepositoryTests.cs
Fixed a flacky test
Closes #498
=> Fixed a flacky test

Eraware_Dnn_Spa_Ef_Di_Stencil/build/Build.cs
=> Pull before pushing when commiting generated files

Eraware_Dnn_Spa_Ef_Di_Stencil/module/build.ps1, Eraware_Dnn_Spa_Ef_Di_Stencil/module/build.sh
Mainly line endings in .sh file needed for linux builds
=> Properly bumps Nuke to 6.0.1

Eraware_Dnn_Spa_Ef_Di_Stencil/module.web/src/components/my-component/my-component.tsx, Eraware_Dnn_Spa_Ef_Di_Stencil/module.web/src/index.ts
This makes the components available automatically to the whole project.
Closes #487
=> Migrated dnn-elements from component to index.ts

Eraware_Dnn_Spa_Ef_Di_Stencil/build/Build.cs
Improved logging for release notes generation
Closes #499
=> Improved logging for release notes generation

Eraware_Dnn_Spa_Ef_Di_Stencil/build/Build.cs
=> Hardened exception handling for github api call

Eraware_Dnn_Spa_Ef_Di_Stencil/build/Build.cs
Adds missing System.Threading.Tasks import
=> Adds missing System.Threading.Tasks import

Eraware_Dnn_Spa_Ef_Di_Stencil/module.web/package.json
Simplified @stencil/eslint-plugin dependency
=> Simplified @stencil/eslint-plugin dependency

Eraware_Dnn_Spa_Ef_Di_Stencil/build/Build.cs
=> Fixed an issue that preventing releasing on release branches

Eraware_Dnn_Spa_Ef_Di_Stencil/module.web/package.json
=> Fixed an issue where initial package would fail due to tsdoc task

Eraware_Dnn_Spa_Ef_Di_Stencil/Eraware_Dnn_Spa_Ef_Di_Stencil.csproj
Fixed an issue where DocFx would fail on ToolsVersion="15.0"
=> Fixed an issue where DocFx would fail on ToolsVersion="15.0"

Eraware_Dnn_Spa_Ef_Di_Stencil/build/ProjectTemplate.csproj
This resolves a module build issue.
=> Bumped docfx to v2.59.4

Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/Data/Repositories/GenericRepositoryTests.cs
=> Fixed a flaky unit test

Eraware_Dnn_Spa_Ef_Di_Stencil/IntegrationTests/ProjectTemplate.csproj, Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/ProjectTemplate.csproj, Eraware_Dnn_Spa_Ef_Di_Stencil/module/ProjectTemplate.csproj, Eraware_Dnn_Spa_Ef_Di_Stencil/module/manifest.dnn
Bumped DNN dependency to v9.11.2
=> Bumped DNN dependency to v9.11.2

Eraware_Dnn_Spa_Ef_Di_Stencil/build/Build.cs, Eraware_Dnn_Spa_Ef_Di_Stencil/build/ProjectTemplate.csproj
=> Bumped GitVersion to v5.10.1

Eraware_Dnn_Spa_Ef_Di_Stencil/build/Build.cs, Eraware_Dnn_Spa_Ef_Di_Stencil/module/.gitignore
Combined ci builds to have 1 build instead of 3
Closes #500
=> Combined ci builds to have 1 build instead of 3

Eraware_Dnn_Spa_Ef_Di_Stencil/build/Build.cs, Eraware_Dnn_Templates/Properties/AssemblyInfo.cs, Eraware_Dnn_Templates/source.extension.vsixmanifest
=> Enabled CI Ubuntu build

Eraware_Dnn_Templates/source.extension.vsixmanifest
Bumped version to v1.5.0 for next release
=> Bumped version to v1.5.0 for next release

Eraware_Dnn_Templates/source.extension.vsixmanifest
Bumped version to v1.5.1 for next release
=> Bumped version to v1.5.1 for next release

.github/dependabot.yml, Eraware_Dnn_Spa_Ef_Di_Stencil/module/.github/dependabot.yml
=> Added dependabot groups

Eraware_Dnn_Spa_Ef_Di_Stencil/IntegrationTests/ProjectTemplate.csproj, Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/ProjectTemplate.csproj, Eraware_Dnn_Spa_Ef_Di_Stencil/build/Build.cs, Eraware_Dnn_Spa_Ef_Di_Stencil/module/ProjectTemplate.csproj
Bumped DNN dependency to 9.13.4
=> Bumped DNN dependency to 9.13.4

Eraware_Dnn_Spa_Ef_Di_Stencil/build/Build.cs, Eraware_Dnn_Spa_Ef_Di_Stencil/build/ProjectTemplate.csproj, Eraware_Dnn_Spa_Ef_Di_Stencil/module/build.ps1, Eraware_Dnn_Spa_Ef_Di_Stencil/module/build.sh, Eraware_Dnn_Spa_Ef_Di_Stencil/module/global.json
=> Bumped Nuke to v8.0.0

Eraware_Dnn_Spa_Ef_Di_Stencil/build/Build.cs, Eraware_Dnn_Spa_Ef_Di_Stencil/build/ProjectTemplate.csproj, Eraware_Dnn_Spa_Ef_Di_Stencil/module/Controllers/ItemController.cs, Eraware_Dnn_Spa_Ef_Di_Stencil/module/ProjectTemplate.csproj, Eraware_Dnn_Spa_Ef_Di_Stencil/module/manifest.dnn
Adjusted usage of NSwag per breaking changes
=> Adjusted usage of NSwag per breaking changes

.github/dependabot.yml
Updated dependabot.yml that had errors
=> Updated dependabot.yml that had errors

Eraware_Dnn_Spa_Ef_Di_Stencil/build/Build.cs, Eraware_Dnn_Spa_Ef_Di_Stencil/module.web/package.json, Eraware_Dnn_Spa_Ef_Di_Stencil/module.web/tsconfig.json
Fixed some typos and bugs after dependency updates
=> Fixed some typos and bugs after dependency updates

Eraware_Dnn_Spa_Ef_Di_Stencil/IntegrationTests/ProjectTemplate.csproj, Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/ProjectTemplate.csproj
=> Bumped xunit to v2.9.0

Eraware_Dnn_Spa_Ef_Di_Stencil/IntegrationTests/ProjectTemplate.csproj, Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/ProjectTemplate.csproj
=> Bumped Moq to v4.20.70

.github/dependabot.yml, Eraware_Dnn_Spa_Ef_Di_Stencil/IntegrationTests/ProjectTemplate.csproj, Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/ProjectTemplate.csproj, Eraware_Dnn_Spa_Ef_Di_Stencil/module/.github/dependabot.yml
=> Bumped coverlet to 6.0.1

Eraware_Dnn_Spa_Ef_Di_Stencil/build/Build.cs
=> Disabled caching in CI builds

Eraware_Dnn_Spa_Ef_Di_Stencil/IntegrationTests/ProjectTemplate.csproj, Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/ProjectTemplate.csproj
=> Bumped Effort.EF6 to v2.2.17

Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/Controllers/ModuleExceptionFilterAttributeTests.cs
=> Fixed an async unit test

Eraware_Dnn_Spa_Ef_Di_Stencil/build/Build.cs
=> Adjusted module build to publish build artifacts

Eraware_Dnn_Spa_Ef_Di_Stencil/module/docfx_project/articles/git.md
Also adds and corrects some other documentation
Closes #610
=> Added documentation about kgithub actions permissions

Eraware_Dnn_Spa_Ef_Di_Stencil/IntegrationTests/Controllers/ItemControllerTests.cs, Eraware_Dnn_Spa_Ef_Di_Stencil/IntegrationTests/Controllers/ServiceRouteMapperTests.cs, Eraware_Dnn_Spa_Ef_Di_Stencil/IntegrationTests/ProjectTemplate.csproj, Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/Controllers/ItemControllerTests.cs, Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/Controllers/LocalizationControllerTests.cs, Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/Controllers/ServiceRouteMapperTests.cs, Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/Data/Repositories/GenericRepositoryTests.cs, Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/ProjectTemplate.csproj, Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/Providers/DateTimeProviderTests.cs, Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/Services/Items/CreateItemDtoValidatorTests.cs, Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/Services/Items/ItemServiceTests.cs, Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/Services/Items/UpdateItemDtoValidatorTests.cs
=> Replaced Moq with NSubstitute

build/Build.cs
=> Fixed some issues with packaging and versioning

Eraware_Dnn_Spa_Ef_Di_Stencil/build/ProjectTemplate.csproj, Eraware_Dnn_Spa_Ef_Di_Stencil/module/ProjectTemplate.csproj, Eraware_Dnn_Spa_Ef_Di_Stencil/module/manifest.dnn, Eraware_PersonaBarModuleTemplate/_build/ProjectTemplate.csproj, Eraware_PersonaBarModuleTemplate/module/ProjectTemplate.csproj, Eraware_PersonaBarModuleTemplate/module/manifest.dnn
=> Bumped NSwag to v14.2.0

.nuke/build.schema.json, Eraware_Dnn_Templates/source.extension.vsixmanifest, build/Build.cs
Fixed an issue with versioning
=> Fixed an issue with versioning

Eraware_Dnn_Spa_Ef_Di_Stencil/build/ProjectTemplate.csproj, Eraware_PersonaBarModuleTemplate/_build/ProjectTemplate.csproj
Bumped ReportGenerator to v5.4.2
=> Bumped ReportGenerator to v5.4.2

Eraware_Dnn_Spa_Ef_Di_Stencil/build/Helpers.cs, Eraware_Dnn_Spa_Ef_Di_Stencil/build/ProjectTemplate.csproj, Eraware_Dnn_Spa_Ef_Di_Stencil/module/global.json, Eraware_PersonaBarModuleTemplate/_build/ProjectTemplate.csproj, Eraware_PersonaBarModuleTemplate/module/global.json, build/_build.csproj
=> Bumped nuke to v9.0.3

Eraware_Dnn_Spa_Ef_Di_Stencil/module/manifest.dnn, Eraware_PersonaBarModuleTemplate/module/manifest.dnn
Fixed some missing assembly references in manifests
=> Fixed some missing assembly references in manifests

Eraware_Dnn_Templates/source.extension.vsixmanifest, build/Build.cs
=> Released `v1.8.1`
